-- Source provenance + synthesis audit trail.
-- These tables support the long-term model where ballot-page content is
-- scraped from verified sources and regenerated by AI only when material
-- changes occur.

create table public.sources (
  id              uuid primary key default gen_random_uuid(),
  source_type     text not null check (source_type in (
                    'official', 'campaign', 'news', 'rss', 'api',
                    'social', 'polling', 'civic', 'other'
                  )),
  trust_tier      text not null default 'standard' check (trust_tier in (
                    'official', 'verified', 'standard', 'limited'
                  )),
  url             text not null unique,
  canonical_url   text,
  publisher       text,
  author          text,
  title           text,
  excerpt         text,
  published_at    timestamptz,
  fetched_at      timestamptz not null default now(),
  raw_hash        text,
  status          text not null default 'active' check (status in (
                    'active', 'stale', 'retracted', 'blocked', 'error'
                  )),
  metadata        jsonb not null default '{}'::jsonb,
  created_at      timestamptz not null default now()
);

create index sources_type_idx on public.sources(source_type, trust_tier);
create index sources_published_idx on public.sources(published_at desc);
create index sources_hash_idx on public.sources(raw_hash);

create table public.source_evidence_links (
  id            uuid primary key default gen_random_uuid(),
  source_id     uuid not null references public.sources(id) on delete cascade,
  target_type   text not null check (target_type in (
                  'race', 'candidate', 'issue', 'endorsement', 'poll', 'news_item'
                )),
  target_id     text not null,
  field_name    text,
  claim         text,
  created_at    timestamptz not null default now()
);

create index source_evidence_source_idx on public.source_evidence_links(source_id);
create index source_evidence_target_idx on public.source_evidence_links(target_type, target_id, field_name);

create table public.material_events (
  id             uuid primary key default gen_random_uuid(),
  event_type      text not null check (event_type in (
                   'campaign_suspension', 'withdrawal', 'candidate_entry',
                   'stance_change', 'endorsement', 'poll_shift', 'major_news',
                   'official_filing', 'correction', 'other'
                 )),
  severity        text not null default 'medium' check (severity in ('low', 'medium', 'high')),
  race_id         text references public.races(id) on delete cascade,
  candidate_id    text references public.candidates(id) on delete cascade,
  summary         text not null,
  source_ids      uuid[] not null default '{}'::uuid[],
  occurred_at     timestamptz,
  detected_at     timestamptz not null default now(),
  status          text not null default 'queued' check (status in (
                   'queued', 'reviewing', 'accepted', 'ignored', 'processed'
                 )),
  metadata        jsonb not null default '{}'::jsonb
);

create index material_events_race_idx on public.material_events(race_id, detected_at desc);
create index material_events_candidate_idx on public.material_events(candidate_id, detected_at desc);
create index material_events_status_idx on public.material_events(status, severity);

create table public.synthesis_runs (
  id              uuid primary key default gen_random_uuid(),
  target_type      text not null check (target_type in ('race', 'candidate', 'issue', 'about')),
  target_id        text not null,
  field_name       text not null,
  trigger_type     text not null default 'manual' check (trigger_type in (
                    'manual', 'scheduled', 'material_event', 'seed'
                  )),
  material_event_id uuid references public.material_events(id) on delete set null,
  status           text not null default 'queued' check (status in (
                    'queued', 'running', 'succeeded', 'failed', 'discarded'
                  )),
  model            text,
  prompt_version   text,
  source_ids       uuid[] not null default '{}'::uuid[],
  input_hash       text,
  output_hash      text,
  started_at       timestamptz,
  completed_at     timestamptz,
  error            text,
  metadata         jsonb not null default '{}'::jsonb,
  created_at       timestamptz not null default now()
);

create index synthesis_runs_target_idx on public.synthesis_runs(target_type, target_id, field_name, created_at desc);
create index synthesis_runs_status_idx on public.synthesis_runs(status, created_at desc);

create table public.synthesized_field_versions (
  id                uuid primary key default gen_random_uuid(),
  synthesis_run_id  uuid references public.synthesis_runs(id) on delete set null,
  target_type       text not null check (target_type in ('race', 'candidate', 'issue', 'about')),
  target_id         text not null,
  field_name        text not null,
  content           text not null,
  source_ids        uuid[] not null default '{}'::uuid[],
  is_current        boolean not null default false,
  created_at        timestamptz not null default now()
);

create index synthesized_versions_target_idx
  on public.synthesized_field_versions(target_type, target_id, field_name, created_at desc);

create unique index synthesized_versions_one_current_idx
  on public.synthesized_field_versions(target_type, target_id, field_name)
  where is_current;

alter table public.sources enable row level security;
alter table public.source_evidence_links enable row level security;
alter table public.material_events enable row level security;
alter table public.synthesis_runs enable row level security;
alter table public.synthesized_field_versions enable row level security;

create policy "public read sources" on public.sources for select using (true);
create policy "public read source evidence" on public.source_evidence_links for select using (true);

-- material_events, synthesis_runs, and synthesized_field_versions are
-- internal audit/job tables. They intentionally have RLS enabled with no
-- public policies; service-role ingestion/synthesis jobs can still access
-- them, but anon clients cannot read drafts, errors, or prompt metadata.
